# Generated by Django 5.0.3 on 2024-05-15 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_book_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='track',
            new_name='track_id',
        ),
    ]
