# Generated by Django 5.0.3 on 2024-05-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_rename_track_question_track_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='track_id',
            new_name='track',
        ),
    ]
