# Generated by Django 5.0.3 on 2024-05-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_rename_track_book_track_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user_id',
            new_name='username',
        ),
    ]
