# Generated by Django 5.0.3 on 2024-05-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_rename_content_answer_answercontent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answerContent',
            new_name='answer_content',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='note_content',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='user_id',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='questionContent',
            new_name='question_content',
        ),
    ]
