# Generated by Django 5.0.3 on 2024-05-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_rename_answercontent_answer_answer_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='track_id',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='track_id',
            new_name='track',
        ),
    ]
